Add FilterHighlightAnnotateOWASP.bambda
PortSwigger/bambdas pull request #26
Opened 2023-12-06 03:01 UTC by flamebarke

### Bambda Contributions

* [ ] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [ ] Bambda compiles and executes as expected
* [ ] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

2023-12-06 03:30 UTC, flamebarke commented
https://www.phrack.me/tools/2023/12/04/Burp-Bambdas.html

2023-12-06 15:37 UTC, Hannah-PortSwigger requested changes
Thank you very much for the submission!

We really like this concept, and it's great to see you've done a blog post on the subject as well.

We've reviewed your Bambda, and have some suggestions relating to the readability of your Bambda, and improvements that could be made to the Java code. 

If you have any issues implementing this feedback, please let us know and we'd be happy to help out.

Thank you again for your contribution to this repository!

2023-12-06 15:37 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterHighlightAnnotateOWASP.bambda
> +* @author Shain Lakin (https://github.com/flamebarke/SkittlesBambda)
Please move line 3 and 4 above the `@author` tag.

2023-12-06 15:37 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterHighlightAnnotateOWASP.bambda
> +// Vulnerable parameters
We'd recommend creating an inner class/record with the name of the vulnerability class,  highlight color, and the list of parameter names. This would simplify your logic later on and make it more readable.

You can find an example here:
```java
record VulnerableParameterGroup(String title, HighlightColor color, String... parameterNames) {}

VulnerableParameterGroup ssrf = new VulnerableParameterGroup("SSRF", HighlightColor.GREEN, "dest", "redirect", "uri", "path", "continue", "url", "window", "next", "data", "reference", "site", "html", "val", "validate", "domain", "callback", "return", "page", "feed", "host", "port", "to", "out", "view", "dir");
```

2023-12-06 15:37 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterHighlightAnnotateOWASP.bambda
> +    String[] allInputParams = (queryString + "&" + requestBody).split("&");
This can use the Montoya API to extract parameters from the request.

We'd recommend checking out the updated version of your inspiration Bambda here, as it now has an example of this: https://github.com/PortSwigger/bambdas/blob/2a6e2a8bdc9b88a78fabdbe1c9b6dc31f1415a25/Proxy/HTTP/OWASPTop25VulnerableParameters.bambda#L37-L43

2023-12-06 15:37 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterHighlightAnnotateOWASP.bambda
> +    }
Depending on how you've implemented the previous feedback for your vulnerability classes, this code will be able to be simplified.

2023-12-07 10:22 UTC, Hannah-PortSwigger approved these changes
Thank you very much for implementing the feedback! This looks great 😄

2023-12-07 10:22 UTC, merged