Update IncorrectContentLength.bambda
PortSwigger/bambdas pull request #43
Opened 2023-12-13 17:02 UTC by soffensive

Edge case

### Bambda Contributions

* [ ] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [ ] Bambda compiles and executes as expected
* [ ] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

2023-12-13 18:17 UTC, PortSwiggerWiener requested changes

2023-12-13 18:17 UTC, PortSwiggerWiener commented on Proxy/HTTP/IncorrectContentLength.bambda
> +if (!requestResponse.hasResponse() || requestResponse.request().method() == "HEAD") {
Good suggestion! Can you please update this to:

requestResponse.request().method().equals("HEAD")

as the == checks reference equality.

2023-12-15 14:50 UTC, PortSwiggerWiener approved these changes
Many thanks for your submission!

Looks good 👍

2023-12-15 14:50 UTC, ps-porpoise approved these changes

2023-12-15 14:51 UTC, merged