feat: Bambda to filter authorization values not equal to jwt bearer
PortSwigger/bambdas pull request #61
Opened 2024-02-28 21:42 UTC by GangGreenTemperTatum

### Bambda Contributions

* [✅] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [✅] Bambda compiles and executes as expected
* [✅] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

The intent of this bambda is to filter the burp suite proxy for in-scope HTTP requests that contain an `Authorization` HTTP header which `!=null`, contains "`bearer`" (case-insensitive) and `!~"ey"`. 

[The JWT header often (not always) starts with {"alg":... , which then becomes eyJ.](https://medium.com/asecuritysite-when-bob-met-alice/tokens-jwt-and-google-tink-c6b915d387e8).. of course, this can be expanded to tailor other types of session-tokens etc.

The use-case for this (which i have tested and used myself) is for testing web app endpoints which use authentication, but is not validated with a traditional bearer token such as JWT (could be an API key for example) which can represent incoherence and weaknesses within endpoint security misconfigurations between the use of session-tokens and API keys for authentication.

Here's an example of my bambda in action:

![image](https://github.com/PortSwigger/bambdas/assets/104169244/85780516-b022-45c3-9e33-7b2be4fb5624)

The goal of identifying web application endpoints that use authentication but are not validated with a traditional bearer token (e.g., JWT or API key) is important for several reasons in terms of application security:

1. **Detection of Misconfigurations:** Misconfigurations in authentication mechanisms can lead to security vulnerabilities. Identifying instances where authentication is in place but not correctly configured with standard bearer tokens helps in detecting potential misconfigurations that might lead to unauthorized access or other security breaches.
2. **Consistency in Security Measures:** Using a consistent approach for authentication across web application endpoints is essential for maintaining a robust security posture. Incoherence in the use of different types of tokens (e.g., session tokens and API keys) can introduce confusion and weaken the overall security of the application.
3. **Prevention of Token Confusion Attacks:** The goal helps in preventing token confusion attacks where an attacker exploits misconfigurations to use one type of token where another is expected. This type of attack can lead to unauthorized access or privilege escalation if not addressed.
4. **Mitigation of Security Weaknesses:** Identifying and addressing security weaknesses related to token validation ensures that the authentication process is reliable and resistant to common attacks. This is crucial for protecting sensitive data, user accounts, and preventing unauthorized actions within the application.
5. **Enhancement of Overall Application Security Posture:** By focusing on the specific aspect of authentication token validation, the goal contributes to an overall enhancement of the application's security posture. It allows developers and security teams to address vulnerabilities and maintain a more secure environment.
6. **Compliance with Security Best Practices:** Following best practices in authentication, such as using standardized bearer tokens, is often recommended for secure web application development. Achieving the goal aligns with these best practices, ensuring that the application adheres to recognized and accepted security standards.
7. **Risk Reduction:** Identifying and rectifying misconfigurations in authentication reduces the risk of unauthorized access, data breaches, and other security incidents. This proactive approach helps in minimizing the potential impact of security threats on the application and its users.

2024-02-29 13:56 UTC, Hannah-PortSwigger requested changes
Thank you very much for your submission!

We have some feedback points for you.

Please let us know if you have any questions, or if there's anything we can help with.

2024-02-29 13:56 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var configNoFilter = true;
We suggest that you remove the filter by MIME type logic from this Bambda in order to simplify it. This functionality is also not directly linked to identifying session/authorization tokens.

2024-02-29 13:56 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var configNotInScopeOnly = true;
We'd recommend renaming this variable to `configInScopeOnly` and setting to `false` to make this Bambda easier to read.

2024-02-29 13:56 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var authHeader = request.hasHeader("Authorization");
if `hasHeader()` doesn't find a result, it will return null, so you do not need to use the ternary below.

2024-02-29 13:56 UTC, Hannah-PortSwigger commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +return (authHeader && authHeaderValue != null && authHeaderValue.length() > 0 && !excludeAuthorization || sessionCookie) && (configNoFilter || filterDenyList) && (!configNotInScopeOnly || request.isI
You can perform the `request.isInScope()` check at the beginning of the Bambda to reduce unnecessary work.

2024-02-29 14:57 UTC, GangGreenTemperTatum commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var configNotInScopeOnly = true;
thanks! good call, see https://github.com/PortSwigger/bambdas/pull/61/commits/79131f201542c558e49ac14cae5b5bffd5f34b55 and working on the other proposals now :)

2024-02-29 16:03 UTC, GangGreenTemperTatum commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var configNotInScopeOnly = true;
hey @Hannah-PortSwigger 

please see [2e29a16](https://github.com/PortSwigger/bambdas/pull/61/commits/2e29a16ff3328f69e54973a470aea352a9f397a8) where i have added some brief comments and renamed the var, but i think when you said:

> and setting to **false** to make this Bambda easier to read.

you actually mean `true`**(?)**, I.E setting the variable to **only** display `in-scope` assets as per the proxy config. i.e, testing this if i set the following and the rest of the code as is as per the above commit:

```java
var configNoFilter = true;
var configInScopeOnly = false; // If set to true, won't show out-of-scope items
var sessionCookieName = ""; // If given, will look for a cookie with that name.
var sessionCookieValue = ""; // If given, will check if cookie with sessionCookieName has this value.
```

my proxy displays out-of-scope domains: (i unredacted Feedly, a browser plugin).

![image](https://github.com/PortSwigger/bambdas/assets/104169244/da9f9a35-5019-465a-a62c-8d5c49e8b5ce)

whereas compared to the artifact in the [PR description](https://github.com/PortSwigger/bambdas/pull/61#issue-2159917988) which is matching my in-scope items and highlighted using pwnfox burp plugin

plmk if i am misunderstanding here and tyia!

2024-02-29 16:14 UTC, GangGreenTemperTatum commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var configNoFilter = true;
[a5952c9](https://github.com/PortSwigger/bambdas/pull/61/commits/a5952c976eae5796a10031a9d38cad61f531558f)

2024-02-29 16:30 UTC, GangGreenTemperTatum commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +var authHeader = request.hasHeader("Authorization");
[chore: restructure hasHeader() and remove ternary](https://github.com/PortSwigger/bambdas/pull/61/commits/d2dc6814b95f4c1d78575468347405347e69dcce)

2024-02-29 16:34 UTC, GangGreenTemperTatum commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +return (authHeader && authHeaderValue != null && authHeaderValue.length() > 0 && !excludeAuthorization || sessionCookie) && (configNoFilter || filterDenyList) && (!configNotInScopeOnly || request.isI
[3b976ed](https://github.com/PortSwigger/bambdas/pull/61/commits/3b976edd95d694ee439de370e72071992292acf0)

2024-02-29 16:40 UTC, GangGreenTemperTatum commented on Proxy/HTTP/FilterAuthenticatedNonBearerTokens.bambda
> +return (authHeader && authHeaderValue != null && authHeaderValue.length() > 0 && !excludeAuthorization || sessionCookie) && (configNoFilter || filterDenyList) && (!configNotInScopeOnly || request.isI
to be honest, i was modeling from [this](https://github.com/PortSwigger/bambdas/blob/36cb075ca72329521a5ec12cccc0b4129d4eaeb5/Proxy/HTTP/FilterAuthenticated.bambda#L51) example published bambda, perhaps i am missing something though

2024-03-01 10:35 UTC, Hannah-PortSwigger commented
@GangGreenTemperTatum Thanks for taking a look! We've made some further adjustments based on the feedback to tidy up the Bambda a bit - can you check whether this still lines up with your original logic?

2024-03-01 13:51 UTC, Hannah-PortSwigger approved these changes

2024-03-01 14:00 UTC, ps-porpoise approved these changes
Looks great, thanks for your submission!

2024-03-01 14:00 UTC, merged