feat: highlight easy param miner requests
PortSwigger/bambdas pull request #76
Opened 2024-07-17 20:51 UTC by GangGreenTemperTatum

### Bambda Contributions

idea is to use this as a bambda, following creation of a custom wordlist from generating/extracting JSON params from an OAPI spec for you to easily identify the `200`'s which you want to throw the wordlist at (IE `extensions > paramminer > guess JSON > custom wordlist` etc.)

* [x] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [x] Bambda compiles and executes as expected
* [x] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

```shell
➜  bambdas-fork git:(ads/createbambdaforparamminer) ✗ java -jar BambdaChecker-1.3.jar validateonly ./Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda
...
Bambda ./Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda parsed correct.
```

2024-07-18 16:00 UTC, Hannah-PortSwigger requested changes
Thanks for your submission!

Please can you review these feedback points?

2024-07-18 16:00 UTC, Hannah-PortSwigger commented on Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda
> + }
You could combine this into a single early return statement, then only initialize variables after the early return.

e.g.
```java
if (!requestResponse.hasResponse() || (configInScopeOnly && !requestResponse.request().isInScope()) || !requestResponse.response().isStatusCodeClass(StatusCodeClass.CLASS_2XX_SUCCESS))
{
    return false;
}

var request = requestResponse.request();
var response = requestResponse.response();
```

2024-07-18 16:00 UTC, Hannah-PortSwigger commented on Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda
> +     if (!requestResponse.hasResponse() || request.method().equals("POST") || request.method().equals("PATCH") || request.method().equals("PUT")) {
Our earlier guard clause means that there will be a response. Therefore, there is no need to check whether a requestResponse has a response.

2024-07-19 11:48 UTC, GangGreenTemperTatum commented on Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda
> + }
nice! thanks and good feedback! 🚀 

fixed and tested ✅ [chore: single early return tidy code feedback](https://github.com/PortSwigger/bambdas/pull/76/commits/285d97bfad96580260331c5c0ebf8f81e33deeb0)

```shell
➜  bambdas-fork git:(ads/createbambdaforparamminer) ✗ java -jar BambdaChecker-1.3.jar validateonly ./Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda
..
Bambda ./Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda parsed correct.
```

2024-07-19 12:06 UTC, GangGreenTemperTatum commented on Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda
> +     if (!requestResponse.hasResponse() || request.method().equals("POST") || request.method().equals("PATCH") || request.method().equals("PUT")) {
again, thank you and love it! much cleaner 🧽 

fixed and tested ✅  [chore: rm redundant code has response earlier clause](https://github.com/PortSwigger/bambdas/pull/76/commits/002c0b694a4334a8a8a24a5db1f5817f3586134c)

```shell
➜  bambdas-fork git:(ads/createbambdaforparamminer) ✗ java -jar BambdaChecker-1.3.jar validateonly ./Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda | grep Param
Bambda ./Filter/Proxy/HTTP/UrlInParameter.bambda parsed correct.
Bambda ./Filter/Proxy/HTTP/ReflectedParameters.bambda parsed correct.
Bambda ./Filter/Proxy/HTTP/HighlightParamMinerTargets.bambda parsed correct.
```

also tested the bambda in BS and proxy history filter is as intended 👌

2024-07-19 12:26 UTC, Hannah-PortSwigger approved these changes
Looks good! Many thanks for your submission 🙂

2024-07-19 12:40 UTC, ibz-odumade-portswigger approved these changes

2024-07-19 12:42 UTC, merged