Create DetectWeakXSSProtectionHeader.bambda
PortSwigger/bambdas pull request #84
Opened 2024-12-18 17:23 UTC by ctflearner

This script checks if the HTTP response contains a weak or misconfigured "X-XSS-Protection" header.

### Bambda Contributions

* [ ] Bambda has a valid [header](https://github.com/PortSwigger/bambdas/blob/73077e7ff3f6fac9db7dc95c0a00bd842b6bb64c/Proxy/HTTP/FilterOnCookieValue.bambda#L1-L5), featuring an `@author` annotation and suitable description
* [ ] Bambda compiles and executes as expected
* [ ] Only .bambda files have been added or modified (README.md files are automatically updated / generated after PR merge)

2025-01-02 14:35 UTC, Hannah-PortSwigger requested changes
Thank you for your contribution, and apologies for the delay over the holiday period.

Could you please review the feedback points below?

2025-01-02 14:35 UTC, Hannah-PortSwigger commented on Filter/Proxy/HTTP/DetectWeakXSSProtectionHeader.bambda
> +            header.value().trim().equals("0")
This could be combined into one statement with:
```java
(header.value().trim().equals("0") || header.value().trim().equals("1") || header.value().toLowerCase(Locale.US).contains("report="))
```

2025-01-02 14:35 UTC, Hannah-PortSwigger commented on Filter/Proxy/HTTP/DetectWeakXSSProtectionHeader.bambda
> +             header.value().toLowerCase().contains("report="))
`toLowerCase()` should specify Locale.

2025-01-02 14:35 UTC, Hannah-PortSwigger commented on Filter/Proxy/HTTP/DetectWeakXSSProtectionHeader.bambda
> +    requestResponse.response().headers().stream()
Would this be better using the built-in `HttpResponse.hasHeader()` functionality?

2025-01-02 14:39 UTC, ctflearner commented
Did i have to change the code in the main file or should i comment the corrected code in the comment ?? Just confirm so that i can change it

2025-01-02 14:54 UTC, Hannah-PortSwigger commented
Hi @ctflearner 

You can change the code yourself, and then we can review your changes.

Please let us know if you have any issues.

2025-01-08 10:58 UTC, Hannah-PortSwigger approved these changes
Thank you for implementing the feedback! This looks good.

2025-01-09 08:51 UTC, PortSwiggerWiener approved these changes
Many thanks for your submission. LGTM 👍

2025-01-09 08:52 UTC, merged